In [127]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [128]:
df = pd.read_csv("test_features.csv")
df.keys()

Index(['Audio_File', 'Amplitude_Envelope_Mean', 'RMS_Mean', 'ZCR_Mean',
       'STFT_Mean', 'SC_Mean', 'SBAN_Mean', 'SCON_Mean', 'MelSpec', 'MFCCs1',
       'MFCCs2', 'MFCCs3', 'MFCCs4', 'MFCCs5', 'MFCCs6', 'MFCCs7', 'MFCCs8',
       'MFCCs9', 'MFCCs10', 'MFCCs11', 'MFCCs12', 'MFCCs13', 'Cry_Reason'],
      dtype='object')

In [129]:
df

Audio_File  \
0    ../data/input_data/audio/belly_pain/999bf14b-e...   
1    ../data/input_data/audio/belly_pain/d6cda191-4...   
2    ../data/input_data/audio/belly_pain/643D64AD-B...   
3    ../data/input_data/audio/belly_pain/643D64AD-B...   
4    ../data/input_data/audio/belly_pain/643D64AD-B...   
..                                                 ...   
444  ../data/input_data/audio/hungry/7A864194-4B6B-...   
445  ../data/input_data/audio/hungry/C421C6FE-DFEE-...   
446  ../data/input_data/audio/hungry/F24DE44B-762C-...   
447  ../data/input_data/audio/hungry/bb2bdafb-0477-...   
448  ../data/input_data/audio/hungry/ca7d8d54-13cb-...   

     Amplitude_Envelope_Mean  RMS_Mean  ZCR_Mean  STFT_Mean      SC_Mean  \
0                   0.029812  0.037048  0.115882   0.221930  1468.367223   
1                   0.030044  0.037441  0.149024   0.248244  1697.507752   
2                   0.032129  0.040675  0.082951   0.255937  1244.038154   
3                   0.021348  0.026666  0.076224   0.129716  1377.876771   
4                   0.005189  0.006370  0.084169   0.035780  1259.114867   
..                       ...       ...       ...        ...          ...   
444                 0.083123  0.100670  0.101564   0.636554  1458.192247   
445                 0.042364  0.055234  0.082977   0.354835  1275.000073   
446                 0.063924  0.074732  0.057155   0.256327   999.091619   
447                 0.078553  0.097674  0.090116   0.615828  1251.202383   
448                 0.061339  0.072039  0.084734   0.242767  1288.239143   

       SBAN_Mean  SCON_Mean   MelSpec     MFCCs1  ...     MFCCs5     MFCCs6  \
0     829.370456  26.642312  0.394583 -424.96246  ...  25.967686 -40.226376   
1     859.914077  26.538055  0.390348 -395.84418  ...  19.919676 -40.894665   
2     978.251150  23.548246  0.698357 -310.27640  ...  11.205345 -51.363796   
3    1106.948005  25.896257  0.336240 -388.35030  ...   0.075010 -47.401638   
4     960.878433  24.998574  0.019432 -496.82108  ...  13.099051 -32.893913   
..           ...        ...       ...        ...  ...        ...        ...   
444   960.442619  24.544996  4.476134 -290.79532  ...   9.368552 -33.669262   
445   917.254960  24.761518  1.092156 -298.06808  ...   5.493597 -38.395184   
446   790.005447  27.563157  2.361415 -356.30070  ...   3.340161 -23.261423   
447   762.409422  26.743719  3.164473 -261.44333  ...   7.224627 -23.537054   
448   896.334437  25.955454  2.734786 -391.20395  ...   3.418215 -32.590210   

        MFCCs7     MFCCs8     MFCCs9   MFCCs10    MFCCs11    MFCCs12  \
0   -20.935383  17.614530  -0.906008 -7.033722  -2.875697  -5.811327   
1     9.511745  13.925349 -28.453733  0.005165   3.250163 -16.113070   
2    -9.742394 -10.510047 -33.263744  0.443679  -9.044739 -22.012964   
3    -0.560953  -9.442457 -33.263090  0.724581  -9.981360 -22.474352   
4    -2.009495  -6.786292 -27.024172 -0.111442  -8.818573 -19.803280   
..         ...        ...        ...       ...        ...        ...   
444   6.551798  -0.882706 -28.345903 -1.057294  -9.896125 -20.148392   
445  -2.482872  -3.744574 -27.058683 -2.037538  -8.209266 -19.597473   
446 -19.162180 -21.880919 -22.350570 -1.029074  -7.597335 -18.271292   
447  -4.619751  -0.765376 -13.520173  0.163075 -10.324136 -17.187378   
448 -11.113023   6.893759  -9.315022 -8.741005  -6.763719  -6.398623   

      MFCCs13  Cry_Reason  
0   -1.627080  belly_pain  
1    0.642554  belly_pain  
2    1.983678  belly_pain  
3    2.193574  belly_pain  
4   -0.009947  belly_pain  
..        ...         ...  
444  6.738956      hungry  
445 -0.191484      hungry  
446 -1.404108      hungry  
447  0.793586      hungry  
448  7.407260      hungry  

[449 rows x 23 columns]

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449 entries, 0 to 448
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Audio_File               449 non-null    object 
 1   Amplitude_Envelope_Mean  449 non-null    float64
 2   RMS_Mean                 449 non-null    float64
 3   ZCR_Mean                 449 non-null    float64
 4   STFT_Mean                449 non-null    float64
 5   SC_Mean                  449 non-null    float64
 6   SBAN_Mean                449 non-null    float64
 7   SCON_Mean                449 non-null    float64
 8   MelSpec                  449 non-null    float64
 9   MFCCs1                   449 non-null    float64
 10  MFCCs2                   449 non-null    float64
 11  MFCCs3                   449 non-null    float64
 12  MFCCs4                   449 non-null    float64
 13  MFCCs5                   449 non-null    float64
 14  MFCCs6                   4

In [131]:
label_encoder = LabelEncoder()
df["Cry_Reason_Encoded"] = label_encoder.fit_transform(df["Cry_Reason"])

In [132]:
 df[["Cry_Reason_Encoded","Cry_Reason"]]

Cry_Reason_Encoded  Cry_Reason
0                     0  belly_pain
1                     0  belly_pain
2                     0  belly_pain
3                     0  belly_pain
4                     0  belly_pain
..                  ...         ...
444                   3      hungry
445                   3      hungry
446                   3      hungry
447                   3      hungry
448                   3      hungry

[449 rows x 2 columns]

In [133]:
X = df.drop(columns=["Audio_File","Cry_Reason", "Cry_Reason_Encoded"] ,axis=1)

In [134]:
y = df[["Cry_Reason_Encoded"]]

In [135]:
X

Amplitude_Envelope_Mean  RMS_Mean  ZCR_Mean  STFT_Mean      SC_Mean  \
0                   0.029812  0.037048  0.115882   0.221930  1468.367223   
1                   0.030044  0.037441  0.149024   0.248244  1697.507752   
2                   0.032129  0.040675  0.082951   0.255937  1244.038154   
3                   0.021348  0.026666  0.076224   0.129716  1377.876771   
4                   0.005189  0.006370  0.084169   0.035780  1259.114867   
..                       ...       ...       ...        ...          ...   
444                 0.083123  0.100670  0.101564   0.636554  1458.192247   
445                 0.042364  0.055234  0.082977   0.354835  1275.000073   
446                 0.063924  0.074732  0.057155   0.256327   999.091619   
447                 0.078553  0.097674  0.090116   0.615828  1251.202383   
448                 0.061339  0.072039  0.084734   0.242767  1288.239143   

       SBAN_Mean  SCON_Mean   MelSpec     MFCCs1     MFCCs2  ...     MFCCs4  \
0     829.370456  26.642312  0.394583 -424.96246  146.32152  ... -10.220895   
1     859.914077  26.538055  0.390348 -395.84418  148.65533  ... -13.160526   
2     978.251150  23.548246  0.698357 -310.27640  170.54625  ...   5.469433   
3    1106.948005  25.896257  0.336240 -388.35030  122.67775  ...  11.015186   
4     960.878433  24.998574  0.019432 -496.82108  150.72594  ...  -0.411891   
..           ...        ...       ...        ...        ...  ...        ...   
444   960.442619  24.544996  4.476134 -290.79532  137.67030  ...  -3.726071   
445   917.254960  24.761518  1.092156 -298.06808  146.16913  ...  -9.634271   
446   790.005447  27.563157  2.361415 -356.30070  106.52677  ...  -9.129832   
447   762.409422  26.743719  3.164473 -261.44333  163.53691  ... -32.367527   
448   896.334437  25.955454  2.734786 -391.20395   95.34874  ...  -6.769781   

        MFCCs5     MFCCs6     MFCCs7     MFCCs8     MFCCs9   MFCCs10  \
0    25.967686 -40.226376 -20.935383  17.614530  -0.906008 -7.033722   
1    19.919676 -40.894665   9.511745  13.925349 -28.453733  0.005165   
2    11.205345 -51.363796  -9.742394 -10.510047 -33.263744  0.443679   
3     0.075010 -47.401638  -0.560953  -9.442457 -33.263090  0.724581   
4    13.099051 -32.893913  -2.009495  -6.786292 -27.024172 -0.111442   
..         ...        ...        ...        ...        ...       ...   
444   9.368552 -33.669262   6.551798  -0.882706 -28.345903 -1.057294   
445   5.493597 -38.395184  -2.482872  -3.744574 -27.058683 -2.037538   
446   3.340161 -23.261423 -19.162180 -21.880919 -22.350570 -1.029074   
447   7.224627 -23.537054  -4.619751  -0.765376 -13.520173  0.163075   
448   3.418215 -32.590210 -11.113023   6.893759  -9.315022 -8.741005   

       MFCCs11    MFCCs12   MFCCs13  
0    -2.875697  -5.811327 -1.627080  
1     3.250163 -16.113070  0.642554  
2    -9.044739 -22.012964  1.983678  
3    -9.981360 -22.474352  2.193574  
4    -8.818573 -19.803280 -0.009947  
..         ...        ...       ...  
444  -9.896125 -20.148392  6.738956  
445  -8.209266 -19.597473 -0.191484  
446  -7.597335 -18.271292 -1.404108  
447 -10.324136 -17.187378  0.793586  
448  -6.763719  -6.398623  7.407260  

[449 rows x 21 columns]

In [136]:
y

Cry_Reason_Encoded
0                     0
1                     0
2                     0
3                     0
4                     0
..                  ...
444                   3
445                   3
446                   3
447                   3
448                   3

[449 rows x 1 columns]

In [137]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

In [138]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [139]:
print(f"Train size: {X_train.shape[0]}")
print(f"Validation size: {X_val.shape[0]}")
print(f"Test size: {X_test.shape[0]}")

Train size: 314
Validation size: 67
Test size: 68


In [140]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42,)
rf_model.fit(X_train,y_train)
y_pred = rf_model.predict(X_val)

/Users/buga/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [141]:
print(confusion_matrix(y_val, y_pred))

[[ 0  0  0  5  0]
 [ 0  0  0  3  0]
 [ 0  0  0  5  0]
 [ 0  0  0 49  0]
 [ 0  0  0  5  0]]


In [142]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00         5
           3       0.73      1.00      0.84        49
           4       0.00      0.00      0.00         5

    accuracy                           0.73        67
   macro avg       0.15      0.20      0.17        67
weighted avg       0.53      0.73      0.62        67



/Users/buga/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/buga/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/buga/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_